name: "tverberg_ipm_0.5"
consensus_type: "tverberg"
topology:
  type: "file"
  num_nodes: 64
  degree: 6
  seed: 42
  topology_file: "configs/topologies/erdos_renyi.txt"
# model:
#   type: "cnn"
#   dataset: "mnist"
model:
  type: "resnet20"
  dataset: "cifar10"
  num_classes: 10
  input_channels: 3
training:
  epochs: 200
  batch_size: 128
  eval_batch_size: 256
  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  consensus_interval: 1
  test_interval: 1
  release_interval: 3
attack:
  byzantine_fraction: 0.33
  bad_clients: [41, 58, 45,  7,  6, 43, 11, 30, 34, 23, 63, 26, 27, 19, 25, 35, 14, 39, 55, 52,  4]
  # bad_clients: []
  attack_type: "ipm"
  global_attack: true
seed: 42
data_dir: "./data_splits"
results_dir: "./results/ipm0.5/"
projection_dim: 2
projection_path: "./configs/projection_mats.npz"
num_gpus: 2
